### ISSUE TITLE
gittyup name

### ISSUE THREAD

**Issue by JulianGro** [disruptek/gittyup#16]
Hello,
I would like to ask if you are up for sharing the Gittyup name.
Right now we are using it for a Git GUI Client https://github.com/Murmele/Gittyup
Most of us (if not all) didn't notice your project before deciding on the name. The projects seem to be different enough that we could just share the name.
I thought I would just ask before we end up upsetting someone by using the name. It's still early days for the project so while we would like to keep the name, it is not set in stone.

**Comment by disruptek** [comment]
No problem at all.  Go nuts.  😁
