### ISSUE TITLE
type mismatch error, when running usage example code

### ISSUE THREAD

**Issue by fbpyr** [disruptek/gittyup#17]
first of: thank you so much for writing this high level git library! 
when running (on nim 1.6.4 , debian) the code example from 
https://github.com/disruptek/gittyup#usage 
(with fixed missing `import uri`) I get the following error: 

![image](https://user-images.githubusercontent.com/73931454/154677970-a69867db-6f42-4bfb-8eab-2f642727075f.png)

it tells me that I provided two strings (which I fully agree with) 
but apparently it expected a proc. how would I change the 
example code to get it working? 
Thank you in advance. 🙂

**Comment by fbpyr** [comment]
..got it to work ☺️   - here my oversimplified example (hopefully helpful for others): 

```nim
import uri, os
import gittyup


const
    url = parseURI"https://github.com/disruptek/gittyup"
    dir = "/some/where/gitty"

os.create_dir(dir)

var res = clone(url, dir)
echo res
```

@disruptek thanks again for this super helpful lib!

**Comment by fbpyr** [comment]
..as I found out with the friendly help of ElegantBeef in the nim chat channel, 
I was just missing another import: 
`import logging`
then the example worked like a charm.. 🙂

**Comment by disruptek** [comment]
Glad you find it useful!  Keep us posted; since switching to the @haxscramper wrapper, gittyup hasn't been successfully used in nimph, though it does compile.  So it needs more testing in real world code... 😉
